package server
import "net/http"
func (s *Server) dashboard(w http.ResponseWriter, r *http.Request) { w.Header().Set("Content-Type","text/html; charset=utf-8"); w.Write([]byte(dashHTML)) }
const dashHTML = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Deposition</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--red:#c44040;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:1000px;margin:0 auto;padding:1rem 1.2rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent;transition:.15s}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.btn-s{border-color:var(--green);color:var(--green)}.btn-s:hover{background:var(--green);color:var(--bg)}.overview{display:flex;gap:1.5rem;margin-bottom:1rem;font-size:.7rem;color:var(--leather)}.overview .stat b{display:block;font-size:1.2rem;color:var(--cream)}.toolbar{display:flex;gap:.5rem;margin-bottom:.8rem;flex-wrap:wrap;align-items:center}.toolbar select,.toolbar input{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.3rem .5rem;font-family:var(--mono);font-size:.72rem;outline:none}.toolbar input{flex:1;min-width:120px}.evt-row{display:flex;align-items:center;gap:.5rem;padding:.3rem .5rem;border-bottom:1px solid var(--bg3);font-size:.72rem}.evt-seq{color:var(--cm);width:35px;flex-shrink:0;font-size:.6rem}.evt-actor{color:var(--rl);width:70px;flex-shrink:0}.evt-action{color:var(--gold);width:80px;flex-shrink:0}.evt-resource{color:var(--leather);width:100px;flex-shrink:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.evt-detail{color:var(--cd);flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.evt-hash{color:var(--cm);font-size:.55rem;width:60px;overflow:hidden;text-overflow:ellipsis}.evt-time{color:var(--cm);font-size:.6rem;width:55px;flex-shrink:0}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Deposition</span></h1><div style="display:flex;gap:.5rem"><button class="btn btn-s" onclick="verify()">Verify Chain</button></div></div>
<div class="main"><div id="upgrade-banner" style="display:none;background:#241e18;border:1px solid #8b3d1a;border-left:3px solid #c45d2c;padding:.6rem 1rem;font-size:.78rem;color:#bfb5a3;margin-bottom:.8rem"><strong style="color:#f0e6d3">Free tier</strong> — 10 items max. <a href="https://stockyard.dev/deposition/" target="_blank" style="color:#e8753a">Upgrade to Pro →</a></div><div class="overview" id="ov"></div>
<div class="toolbar"><input type="text" id="fActor" placeholder="Actor" style="width:80px"><input type="text" id="fAction" placeholder="Action" style="width:80px"><input type="text" id="fSearch" placeholder="Search..." onkeydown="if(event.key==='Enter')load()"><button class="btn btn-p" onclick="load()">Search</button></div>
<div id="list"></div></div>
<script>
async function api(u,o){return(await fetch(u,o)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function timeAgo(d){if(!d)return'';const s=Math.floor((Date.now()-new Date(d))/1e3);if(s<60)return s+'s';if(s<3600)return Math.floor(s/60)+'m';return Math.floor(s/3600)+'h'}
async function init(){const sd=await api('/api/stats');document.getElementById('ov').innerHTML='<div class="stat"><b>'+sd.events+'</b>Events</div><div class="stat"><b>'+sd.actors+'</b>Actors</div><div class="stat"><b style="color:'+(sd.verified?'var(--green)':'var(--red)')+'">'+( sd.verified?'Valid':'TAMPERED')+'</b>Chain</div>';load()}
async function load(){
  const p=new URLSearchParams();const a=document.getElementById('fActor').value;if(a)p.set('actor',a);
  const ac=document.getElementById('fAction').value;if(ac)p.set('action',ac);
  const s=document.getElementById('fSearch').value;if(s)p.set('search',s);p.set('limit','200');
  const d=await api('/api/events?'+p);const events=d.events||[];
  document.getElementById('list').innerHTML=events.length?events.map(e=>
    '<div class="evt-row"><span class="evt-seq">#'+e.seq+'</span><span class="evt-actor">'+esc(e.actor)+'</span><span class="evt-action">'+esc(e.action)+'</span><span class="evt-resource">'+esc(e.resource)+'</span><span class="evt-detail">'+esc(e.detail)+'</span><span class="evt-hash" title="'+esc(e.hash)+'">'+esc(e.hash.substring(0,10))+'</span><span class="evt-time">'+timeAgo(e.created_at)+'</span></div>'
  ).join(''):'<div class="empty">No events yet. Append via POST /api/events</div>'
}
async function verify(){const d=await api('/api/verify');alert(d.valid?'Chain verified: '+d.events_checked+' events checked, all valid.':'CHAIN BROKEN: '+d.error)}
init();setInterval(()=>load(),10000)
fetch('/api/tier').then(r=>r.json()).then(j=>{if(j.tier==='free'){var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'}}).catch(()=>{var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'});
</script></body></html>`
